-- ReVolt AI Supabase setup
-- Run this in the Supabase SQL editor before enabling production submissions/uploads.

create table if not exists public.users (
  id bigint primary key generated by default as identity,
  "openId" text unique not null,
  name text,
  email text,
  "loginMethod" text,
  role text not null default 'user' check (role in ('user', 'admin')),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table if not exists public.contact_inquiries (
  id bigint primary key generated by default as identity,
  name text not null,
  email text not null,
  company text not null,
  phone text not null,
  message text not null,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.evidence_files (
  id bigint primary key generated by default as identity,
  "userId" bigint not null,
  "fileName" text not null,
  "mimeType" text not null,
  "sizeBytes" integer not null,
  "storageKey" text unique not null,
  "storageUrl" text not null,
  "createdAt" timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('revolt-evidence', 'revolt-evidence', true)
on conflict (id) do update set public = true;

alter table public.users enable row level security;
alter table public.contact_inquiries enable row level security;
alter table public.evidence_files enable row level security;

-- The server uses SUPABASE_TOKEN for privileged REST operations. These policies
-- are intentionally restrictive for browser clients and keep public inquiry
-- submission behind the server procedure.
